// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type ArticleDocumentDataSlicesSlice =
  | ArticleContentSlice
  | ArticleHeaderSlice
  | ArticleInstagramPostSlice;

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
  /**
   * Slice Zone field in *Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice>; /**
   * Meta Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

type BlogHomepageDocumentDataSlicesSlice =
  | NewsletterSlice
  | BlogArticleGridSlice
  | BlogInstagramCtaSlice
  | BlogHeroSlice;

/**
 * Content for Blog Homepage documents
 */
interface BlogHomepageDocumentData {
  /**
   * Featured Article field in *Blog Homepage*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_homepage.featured_article
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  featured_article: ContentRelationshipFieldWithData<
    [
      {
        id: "article";
        fields: ["meta_title", "meta_description", "meta_image"];
      },
    ]
  >;

  /**
   * Slice Zone field in *Blog Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogHomepageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Blog Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog Homepage document from Prismic
 *
 * - **API ID**: `blog_homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogHomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BlogHomepageDocumentData>,
    "blog_homepage",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | TeamSlice
  | NewsletterSlice
  | SolutionStepsSlice
  | IssueHighlightSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Menu site → Navigation*
 */
export interface MenuSiteDocumentDataNavigationItem {
  /**
   * Label field in *Menu site → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_site.navigation[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Menu site → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_site.navigation[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "link" | "button"
  >;
}

/**
 * Content for Menu site documents
 */
interface MenuSiteDocumentData {
  /**
   * Site title field in *Menu site*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_site.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta description field in *Menu site*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_site.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Logo field in *Menu site*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_site.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Logo Link field in *Menu site*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_site.logo_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  logo_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Navigation field in *Menu site*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_site.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation: prismic.GroupField<Simplify<MenuSiteDocumentDataNavigationItem>>;
}

/**
 * Menu site document from Prismic
 *
 * - **API ID**: `menu_site`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuSiteDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MenuSiteDocumentData>,
    "menu_site",
    Lang
  >;

export type AllDocumentTypes =
  | ArticleDocument
  | BlogHomepageDocument
  | HomepageDocument
  | MenuSiteDocument;

/**
 * Item in *ArticleContent → Default → Primary → Notes*
 */
export interface ArticleContentSliceDefaultPrimaryNotesItem {
  /**
   * Marker field in *ArticleContent → Default → Primary → Notes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_content.default.primary.notes[].marker
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  marker: prismic.KeyTextField;

  /**
   * Note field in *ArticleContent → Default → Primary → Notes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_content.default.primary.notes[].note
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  note: prismic.RichTextField;
}

/**
 * Primary content in *ArticleContent → Default → Primary*
 */
export interface ArticleContentSliceDefaultPrimary {
  /**
   * Content field in *ArticleContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_content.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Notes field in *ArticleContent → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: article_content.default.primary.notes[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  notes: prismic.GroupField<
    Simplify<ArticleContentSliceDefaultPrimaryNotesItem>
  >;
}

/**
 * Default variation for ArticleContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ArticleContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArticleContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ArticleContent*
 */
type ArticleContentSliceVariation = ArticleContentSliceDefault;

/**
 * ArticleContent Shared Slice
 *
 * - **API ID**: `article_content`
 * - **Description**: ArticleContent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ArticleContentSlice = prismic.SharedSlice<
  "article_content",
  ArticleContentSliceVariation
>;

/**
 * Primary content in *ArticleHeader → Default → Primary*
 */
export interface ArticleHeaderSliceDefaultPrimary {
  /**
   * Title field in *ArticleHeader → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_header.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *ArticleHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_header.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Hero Image field in *ArticleHeader → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article_header.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Author Name field in *ArticleHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_header.default.primary.author_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_name: prismic.KeyTextField;

  /**
   * Author Avatar field in *ArticleHeader → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article_header.default.primary.author_avatar
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  author_avatar: prismic.ImageField<never>;

  /**
   * Published at field in *ArticleHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_header.default.primary.published_at
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  published_at: prismic.KeyTextField;

  /**
   * Read Time field in *ArticleHeader → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: article_header.default.primary.read_time
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  read_time: prismic.NumberField;

  /**
   * Category field in *ArticleHeader → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: article_header.default.primary.category
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<
    "Adozioni" | "Consigli" | "Storie" | "Alimentazione" | "Attività"
  >;
}

/**
 * Default variation for ArticleHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ArticleHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArticleHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ArticleHeader*
 */
type ArticleHeaderSliceVariation = ArticleHeaderSliceDefault;

/**
 * ArticleHeader Shared Slice
 *
 * - **API ID**: `article_header`
 * - **Description**: ArticleHeader
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ArticleHeaderSlice = prismic.SharedSlice<
  "article_header",
  ArticleHeaderSliceVariation
>;

/**
 * Primary content in *ArticleInstagramPost → Default → Primary*
 */
export interface ArticleInstagramPostSliceDefaultPrimary {
  /**
   * Instagram Url field in *ArticleInstagramPost → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: article_instagram_post.default.primary.instagram_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  instagram_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Instagram Text field in *ArticleInstagramPost → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_instagram_post.default.primary.instagram_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  instagram_text: prismic.KeyTextField;
}

/**
 * Default variation for ArticleInstagramPost Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ArticleInstagramPostSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArticleInstagramPostSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ArticleInstagramPost*
 */
type ArticleInstagramPostSliceVariation = ArticleInstagramPostSliceDefault;

/**
 * ArticleInstagramPost Shared Slice
 *
 * - **API ID**: `article_instagram_post`
 * - **Description**: ArticleInstagramPost
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ArticleInstagramPostSlice = prismic.SharedSlice<
  "article_instagram_post",
  ArticleInstagramPostSliceVariation
>;

/**
 * Item in *BlogArticleGrid → Default → Primary → Pinned Articles*
 */
export interface BlogArticleGridSliceDefaultPrimaryPinnedArticlesItem {
  /**
   * Pinned Article field in *BlogArticleGrid → Default → Primary → Pinned Articles*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article_grid.default.primary.pinned_articles[].pinned_article
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  pinned_article: ContentRelationshipFieldWithData<
    [
      {
        id: "article";
        fields: ["meta_title", "meta_description", "meta_image"];
      },
    ]
  >;
}

/**
 * Primary content in *BlogArticleGrid → Default → Primary*
 */
export interface BlogArticleGridSliceDefaultPrimary {
  /**
   * Section Title field in *BlogArticleGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article_grid.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Category Filter field in *BlogArticleGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article_grid.default.primary.category_filter
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category_filter: prismic.SelectField<
    "Adozioni" | "Consigli" | "Storie" | "Alimentazione" | "Attività"
  >;

  /**
   * Max Articles field in *BlogArticleGrid → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article_grid.default.primary.max_articles
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  max_articles: prismic.NumberField;

  /**
   * Show Filters field in *BlogArticleGrid → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: blog_article_grid.default.primary.show_filters
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_filters: prismic.BooleanField;

  /**
   * Show Load More field in *BlogArticleGrid → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: blog_article_grid.default.primary.show_load_more
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_load_more: prismic.BooleanField;

  /**
   * Pinned Articles field in *BlogArticleGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article_grid.default.primary.pinned_articles[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  pinned_articles: prismic.GroupField<
    Simplify<BlogArticleGridSliceDefaultPrimaryPinnedArticlesItem>
  >;
}

/**
 * Default variation for BlogArticleGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogArticleGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogArticleGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogArticleGrid*
 */
type BlogArticleGridSliceVariation = BlogArticleGridSliceDefault;

/**
 * BlogArticleGrid Shared Slice
 *
 * - **API ID**: `blog_article_grid`
 * - **Description**: BlogArticleGrid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogArticleGridSlice = prismic.SharedSlice<
  "blog_article_grid",
  BlogArticleGridSliceVariation
>;

/**
 * Primary content in *BlogHero → Default → Primary*
 */
export interface BlogHeroSliceDefaultPrimary {
  /**
   * Title field in *BlogHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *BlogHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for BlogHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogHero*
 */
type BlogHeroSliceVariation = BlogHeroSliceDefault;

/**
 * BlogHero Shared Slice
 *
 * - **API ID**: `blog_hero`
 * - **Description**: BlogHero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogHeroSlice = prismic.SharedSlice<
  "blog_hero",
  BlogHeroSliceVariation
>;

/**
 * Item in *BlogInstagramCta → Default → Primary → Images Section*
 */
export interface BlogInstagramCtaSliceDefaultPrimaryImagesSectionItem {
  /**
   * Image field in *BlogInstagramCta → Default → Primary → Images Section*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_instagram_cta.default.primary.images_section[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *BlogInstagramCta → Default → Primary*
 */
export interface BlogInstagramCtaSliceDefaultPrimary {
  /**
   * Title field in *BlogInstagramCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_instagram_cta.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *BlogInstagramCta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_instagram_cta.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button Text field in *BlogInstagramCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_instagram_cta.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *BlogInstagramCta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_instagram_cta.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Images Section field in *BlogInstagramCta → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_instagram_cta.default.primary.images_section[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  images_section: prismic.GroupField<
    Simplify<BlogInstagramCtaSliceDefaultPrimaryImagesSectionItem>
  >;
}

/**
 * Default variation for BlogInstagramCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogInstagramCtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogInstagramCtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogInstagramCta*
 */
type BlogInstagramCtaSliceVariation = BlogInstagramCtaSliceDefault;

/**
 * BlogInstagramCta Shared Slice
 *
 * - **API ID**: `blog_instagram_cta`
 * - **Description**: BlogInstagramCta
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogInstagramCtaSlice = prismic.SharedSlice<
  "blog_instagram_cta",
  BlogInstagramCtaSliceVariation
>;

/**
 * Item in *Hero → Default → Primary → Button*
 */
export interface HeroSliceDefaultPrimaryButtonItem {
  /**
   * Button Text field in *Hero → Default → Primary → Button*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button[].button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button href field in *Hero → Default → Primary → Button*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button[].button_href
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_href: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title 1 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title_1
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_1: prismic.KeyTextField;

  /**
   * Title 2 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title_2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_2: prismic.KeyTextField;

  /**
   * Paragraph field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  paragraph: prismic.KeyTextField;

  /**
   * Hero Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  button: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryButtonItem>>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *IssueHighlight → Default → Primary*
 */
export interface IssueHighlightSliceDefaultPrimary {
  /**
   * Label field in *IssueHighlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: issue_highlight.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Title field in *IssueHighlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: issue_highlight.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *IssueHighlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: issue_highlight.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Stat Label field in *IssueHighlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: issue_highlight.default.primary.stat_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  stat_label: prismic.KeyTextField;

  /**
   * Stat sublabel field in *IssueHighlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: issue_highlight.default.primary.stat_sublabel
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  stat_sublabel: prismic.KeyTextField;

  /**
   * Stat Number field in *IssueHighlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: issue_highlight.default.primary.stat_number
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  stat_number: prismic.KeyTextField;
}

/**
 * Default variation for IssueHighlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IssueHighlightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IssueHighlightSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IssueHighlight*
 */
type IssueHighlightSliceVariation = IssueHighlightSliceDefault;

/**
 * IssueHighlight Shared Slice
 *
 * - **API ID**: `issue_highlight`
 * - **Description**: IssueHighlight
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IssueHighlightSlice = prismic.SharedSlice<
  "issue_highlight",
  IssueHighlightSliceVariation
>;

/**
 * Primary content in *Newsletter → Default → Primary*
 */
export interface NewsletterSliceDefaultPrimary {
  /**
   * Title field in *Newsletter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Newsletter → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Email Placeholder field in *Newsletter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.default.primary.email_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_placeholder: prismic.KeyTextField;

  /**
   * Button text field in *Newsletter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button link field in *Newsletter → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Newsletter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsletterSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Newsletter → Full Width → Primary*
 */
export interface NewsletterSliceFullWidthPrimary {
  /**
   * Title field in *Newsletter → Full Width → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.fullWidth.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Newsletter → Full Width → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.fullWidth.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Email Placeholder field in *Newsletter → Full Width → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.fullWidth.primary.email_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_placeholder: prismic.KeyTextField;

  /**
   * Button text field in *Newsletter → Full Width → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.fullWidth.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button link field in *Newsletter → Full Width → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.fullWidth.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Full Width variation for Newsletter Slice
 *
 * - **API ID**: `fullWidth`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSliceFullWidth = prismic.SharedSliceVariation<
  "fullWidth",
  Simplify<NewsletterSliceFullWidthPrimary>,
  never
>;

/**
 * Slice variation for *Newsletter*
 */
type NewsletterSliceVariation =
  | NewsletterSliceDefault
  | NewsletterSliceFullWidth;

/**
 * Newsletter Shared Slice
 *
 * - **API ID**: `newsletter`
 * - **Description**: Newsletter
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSlice = prismic.SharedSlice<
  "newsletter",
  NewsletterSliceVariation
>;

/**
 * Primary content in *SolutionSteps → Default → Primary*
 */
export interface SolutionStepsSliceDefaultPrimary {
  /**
   * Title field in *SolutionSteps → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solution_steps.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *SolutionSteps → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solution_steps.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * Primary content in *SolutionSteps → Items*
 */
export interface SolutionStepsSliceDefaultItem {
  /**
   * Step Number field in *SolutionSteps → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: solution_steps.items[].step_number
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  step_number: prismic.NumberField;

  /**
   * Image field in *SolutionSteps → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: solution_steps.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Step Title field in *SolutionSteps → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solution_steps.items[].step_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  step_title: prismic.KeyTextField;

  /**
   * Step Description field in *SolutionSteps → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solution_steps.items[].step_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  step_description: prismic.RichTextField;
}

/**
 * Default variation for SolutionSteps Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SolutionStepsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SolutionStepsSliceDefaultPrimary>,
  Simplify<SolutionStepsSliceDefaultItem>
>;

/**
 * Slice variation for *SolutionSteps*
 */
type SolutionStepsSliceVariation = SolutionStepsSliceDefault;

/**
 * SolutionSteps Shared Slice
 *
 * - **API ID**: `solution_steps`
 * - **Description**: SolutionSteps
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SolutionStepsSlice = prismic.SharedSlice<
  "solution_steps",
  SolutionStepsSliceVariation
>;

/**
 * Primary content in *Team → Default → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * Title field in *Team → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *Team → Items*
 */
export interface TeamSliceDefaultItem {
  /**
   * Avatar field in *Team → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].avatar
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  avatar: prismic.ImageField<never>;

  /**
   * Name field in *Team → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Role field in *Team → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSliceDefaultPrimary>,
  Simplify<TeamSliceDefaultItem>
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamSlice = prismic.SharedSlice<"team", TeamSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataSlicesSlice,
      BlogHomepageDocument,
      BlogHomepageDocumentData,
      BlogHomepageDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      MenuSiteDocument,
      MenuSiteDocumentData,
      MenuSiteDocumentDataNavigationItem,
      AllDocumentTypes,
      ArticleContentSlice,
      ArticleContentSliceDefaultPrimaryNotesItem,
      ArticleContentSliceDefaultPrimary,
      ArticleContentSliceVariation,
      ArticleContentSliceDefault,
      ArticleHeaderSlice,
      ArticleHeaderSliceDefaultPrimary,
      ArticleHeaderSliceVariation,
      ArticleHeaderSliceDefault,
      ArticleInstagramPostSlice,
      ArticleInstagramPostSliceDefaultPrimary,
      ArticleInstagramPostSliceVariation,
      ArticleInstagramPostSliceDefault,
      BlogArticleGridSlice,
      BlogArticleGridSliceDefaultPrimaryPinnedArticlesItem,
      BlogArticleGridSliceDefaultPrimary,
      BlogArticleGridSliceVariation,
      BlogArticleGridSliceDefault,
      BlogHeroSlice,
      BlogHeroSliceDefaultPrimary,
      BlogHeroSliceVariation,
      BlogHeroSliceDefault,
      BlogInstagramCtaSlice,
      BlogInstagramCtaSliceDefaultPrimaryImagesSectionItem,
      BlogInstagramCtaSliceDefaultPrimary,
      BlogInstagramCtaSliceVariation,
      BlogInstagramCtaSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryButtonItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      IssueHighlightSlice,
      IssueHighlightSliceDefaultPrimary,
      IssueHighlightSliceVariation,
      IssueHighlightSliceDefault,
      NewsletterSlice,
      NewsletterSliceDefaultPrimary,
      NewsletterSliceFullWidthPrimary,
      NewsletterSliceVariation,
      NewsletterSliceDefault,
      NewsletterSliceFullWidth,
      SolutionStepsSlice,
      SolutionStepsSliceDefaultPrimary,
      SolutionStepsSliceDefaultItem,
      SolutionStepsSliceVariation,
      SolutionStepsSliceDefault,
      TeamSlice,
      TeamSliceDefaultPrimary,
      TeamSliceDefaultItem,
      TeamSliceVariation,
      TeamSliceDefault,
    };
  }
}
