import type { Metadata } from "next";
import { Fredoka, Urbanist } from "next/font/google";
import "./globals.css";

export const fredoka = Fredoka({
  subsets: ["latin"],
  weight: ["500", "600"], // Medium + SemiBold
  variable: "--font-fredoka",
});

export const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-urbanist",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fredoka.variable} ${urbanist.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
